### ISSUE TITLE
Markdown giving incorrect section numbers

### ISSUE THREAD

**Issue by qntm** [qntm/fastjson#1]
Anybody know why Markdown is choosing to take "9. Parsers" and "10. Generators" and render them as "1. Parsers" and "1. Generators" respectively? More pertinently, how to prevent this?

**Comment by tobypinder** [comment]
Attempted in #2, it's a (bad) part of standard Markdown that "lists" always reset from 1.

**Comment by qntm** [comment]
This'll do for now. Thanks for the quick turnaround!
