### ISSUE TITLE
README is missing benchmarks

### ISSUE THREAD

**Issue by worm-emoji** [qntm/fastjson#5]
I get it. This is a standards compliant JSON (de)serializer. Pure JavaScript. Great. 

But this project is called fastjson. And the project README doesn’t sell me that it’s faster. I recommend adding benchmarks to back up your claims if you want to get any sort of real world adoption.

**Comment by Jarred-Sumner** [comment]
+1

**Comment by Lectem** [comment]
Couldn't agree more! 
If it's faster than JSON.parse(), on what platform? cpu?
Node.js ? Chrome ? Firefox ?

**Comment by formigone** [comment]
This is both hilarious and infuriating. Anyone taking this project serious should take 10 seconds and look at the implementation.

```js
module.exports = {
  parse: () => null,
  stringify: () => 'null'
}
```

Better yet, take 60 seconds and read his docs.

> ...The method fastjson.parse takes advantage of [the JSON spec not specifying that the output of `parse` and `stringify` should actually represent the input data] to implement a strictly standards-compliant JSON [library] by returning the JavaScript value `null` **regardless of input**.

Very mind blowing that the project has a few stars and forks. Anyone attempting to run the code will quickly realize this project is a dumb joke. Thanks for wasting my time, @qntm...

**Comment by qntm** [comment]
I apologise for wasting your time with my frivolous joke package. It is probably *massively* unlikely that I could implement a more performant JSON library than the existing native implementations of `JSON.parse` and `JSON.stringify`. However, I appreciate the vote of confidence.

I do intend to try to add benchmarks to this repo at some point. This is a valid issue and I plan to leave it open.

**Comment by formigone** [comment]
It's all good. I actually cloned your repo and ran some benchmarks locally with some realistic data for my use case. The results looked crazy good. Then I decided to make sure your output was the same as `JSON.stringify`, and that's when I noticed what you're doing.

One friendly suggestion: could you add some sort of messaging that this isn't a real project if you really feel the need to keep a joke project on npm? If not in the docs, maybe as an npm install callback? For those looking for a real way to optimize their code, having one less project to go through is appreciated.

**Comment by qntm** [comment]
I will think about better ways to communicate that. I feel like the docs do a fairly clear job of explaining just how useless both this repo and RFC 7159 are, but I have never liked the kind of developer who thinks "you should have scrutinised the documentation from cover to cover before complaining, dimwit" is an acceptable response to a design issue in their software, and I would definitely like to avoid *being* that developer. On the other hand, it might be that I decide that small amounts of wasted time are part of the joke. I may open a separate issue to discuss this.
